name: Go

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Parse Gosec Output
        id: parse_output
        run: |
          VULNERABILITIES=$(grep -o 'Total issues: [0-9]*' gosec_output.txt | awk '{print $3}')
          echo "vulnerabilities=${VULNERABILITIES}" >> $GITHUB_OUTPUT

      - name: Set Vulnerability Count
        run: echo "VULNERABILITY_COUNT=${{ steps.parse_output.outputs.vulnerabilities }}" >> $GITHUB_ENV

      - name: Update README.md with Vulnerability Count
        run: sed -i "s/X/${{ env.VULNERABILITY_COUNT }}/g" README.md

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint, security-scan]
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USERNAME: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
    services:
        mysql:
          image: mysql:8.0
          env:
            MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
            MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          ports:
            - '3306:3306'
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display DB_NAME
        run: echo $DB_NAME

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};' -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }}

      - name: Run Tests with Code Coverage
        run: go test ./... -covermode=count -coverpkg=./... -v -coverprofile=coverage.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: abdullahkabakk/url-shortener

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build App
        run: |
          go build -v ./...
