name: Go

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  commit-message-check-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Commit Message Tag
        run: |
          COMMIT_MSG="$(git log --format=%s -n 1)"
          echo "Commit message: $COMMIT_MSG"
          if [[ ! "$COMMIT_MSG" =~ ^\[[a-zA-Z]+\] ]]; then
            echo "Error: Commit message must start with a tag [feat], [fix], [chore], [docs], [style], [refactor], [test], [ci], [build], or [perf]"
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build App
        run: |
          go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          go test -v ./...
